import {
  Smartphone,
  Router,
  Lightbulb,
  Shield,
  Camera,
  Activity,
  Cpu,
  Settings,
} from 'lucide-react'

export const mockDevicesData = {
  success: true,
  code: 200,
  message: 'Devices data retrieved successfully',
  data: {
    devices: [
      {
        id: 1,
        name: 'ESP32-01',
        type: 'ESP32 DevKit',
        status: 'online',
        location: 'Living Room',
        lastSeen: '2 minutes ago',
        icon: Smartphone,
        firmwareVersion: 'v2.1.0',
        chipId: '240AC4A1B2C8',
      },
      {
        id: 2,
        name: 'ESP32-02',
        type: 'ESP32-S3',
        status: 'online',
        location: 'Workshop',
        lastSeen: '1 minute ago',
        icon: Router,
        firmwareVersion: 'v2.3.1',
        chipId: 'ESP32S3',
      },
      {
        id: 3,
        name: 'Raspberry Pi 4B',
        type: 'Single Board Computer',
        status: 'online',
        location: 'Server Room',
        lastSeen: '30 seconds ago',
        icon: Router,
        firmwareVersion: 'Raspbian 11',
        chipId: 'BCM2711',
      },
      {
        id: 4,
        name: 'Smart Lamp Controller',
        type: 'ESP8266 NodeMCU',
        status: 'offline',
        location: 'Bedroom',
        lastSeen: '2 hours ago',
        icon: Lightbulb,
        firmwareVersion: 'v3.0.2',
        chipId: 'ESP8266EX',
      },
      {
        id: 5,
        name: 'Door Lock Module',
        type: 'ESP32-C3',
        status: 'online',
        location: 'Front Door',
        lastSeen: '5 minutes ago',
        icon: Shield,
        firmwareVersion: 'v1.9.4',
        chipId: 'ESP32C3',
      },
      {
        id: 6,
        name: 'Security Camera Hub',
        type: 'Raspberry Pi Zero 2W',
        status: 'online',
        location: 'Garage',
        lastSeen: '3 minutes ago',
        icon: Camera,
        firmwareVersion: 'Raspbian Lite',
        chipId: 'RP3A0-AU',
      },
      {
        id: 7,
        name: 'Orange Pi 5',
        type: 'Orange Pi Board',
        status: 'online',
        location: 'Lab',
        lastSeen: '1 minute ago',
        icon: Router,
        firmwareVersion: 'Ubuntu 22.04',
        chipId: 'RK3588S',
      },
      {
        id: 8,
        name: 'Weather Station',
        type: 'Wemos D1 Mini',
        status: 'online',
        location: 'Garden',
        lastSeen: '4 minutes ago',
        icon: Activity,
        firmwareVersion: 'v2.7.4',
        chipId: 'ESP8266',
      },
      {
        id: 9,
        name: 'IoT Sensor Hub',
        type: 'Wemos D1 R32',
        status: 'online',
        location: 'Basement',
        lastSeen: '2 minutes ago',
        icon: Cpu,
        firmwareVersion: 'v1.0.6',
        chipId: 'ESP32',
      },
      {
        id: 10,
        name: 'Home Automation',
        type: 'Orange Pi Zero 2W',
        status: 'offline',
        location: 'Control Room',
        lastSeen: '6 hours ago',
        icon: Settings,
        firmwareVersion: 'Armbian 23.02',
        chipId: 'H618',
      },
    ],
    statistics: {
      totalDevices: 10,
      activeDevices: 8,
      offlineDevices: 2,
      newDevicesThisWeek: 3,
    },
  },
  meta: {
    total: 10,
    page: 1,
    limit: 10,
    totalPages: 1,
  },
  timestamp: new Date().toISOString(),
}
