/**
 * Virtual Pins API Response
 * Mock API response for available virtual pins (V1-V50) for sensor and action datapoints
 */

export const virtualPinsResponse = {
  success: true,
  code: 200,
  message: 'Virtual pins retrieved successfully',
  data: {
    virtualPins: [
      { id: 1, value: 'V1' },
      { id: 2, value: 'V2' },
      { id: 3, value: 'V3' },
      { id: 4, value: 'V4' },
      { id: 5, value: 'V5' },
      { id: 6, value: 'V6' },
      { id: 7, value: 'V7' },
      { id: 8, value: 'V8' },
      { id: 9, value: 'V9' },
      { id: 10, value: 'V10' },
      { id: 11, value: 'V11' },
      { id: 12, value: 'V12' },
      { id: 13, value: 'V13' },
      { id: 14, value: 'V14' },
      { id: 15, value: 'V15' },
      { id: 16, value: 'V16' },
      { id: 17, value: 'V17' },
      { id: 18, value: 'V18' },
      { id: 19, value: 'V19' },
      { id: 20, value: 'V20' },
      { id: 21, value: 'V21' },
      { id: 22, value: 'V22' },
      { id: 23, value: 'V23' },
      { id: 24, value: 'V24' },
      { id: 25, value: 'V25' },
      { id: 26, value: 'V26' },
      { id: 27, value: 'V27' },
      { id: 28, value: 'V28' },
      { id: 29, value: 'V29' },
      { id: 30, value: 'V30' },
      { id: 31, value: 'V31' },
      { id: 32, value: 'V32' },
      { id: 33, value: 'V33' },
      { id: 34, value: 'V34' },
      { id: 35, value: 'V35' },
      { id: 36, value: 'V36' },
      { id: 37, value: 'V37' },
      { id: 38, value: 'V38' },
      { id: 39, value: 'V39' },
      { id: 40, value: 'V40' },
      { id: 41, value: 'V41' },
      { id: 42, value: 'V42' },
      { id: 43, value: 'V43' },
      { id: 44, value: 'V44' },
      { id: 45, value: 'V45' },
      { id: 46, value: 'V46' },
      { id: 47, value: 'V47' },
      { id: 48, value: 'V48' },
      { id: 49, value: 'V49' },
      { id: 50, value: 'V50' },
    ],
  },
  meta: {
    total: 50,
    timestamp: new Date().toISOString(),
  },
}
